apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: 916863632898.dkr.ecr.us-east-1.amazonaws.com/server:latest
          command: ["bash", "-c", "npx prisma migrate deploy && npx prisma db seed"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
      restartPolicy: Never
